services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=My3xTr4S3cur3U53r
      - POSTGRES_PASSWORD=My3xTr4!S3cur39455w0rd!!
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      # $ sudo rm -Rf ./local/pgdata && sudo mkdir ./local/pgdata && sudo chown -Rf 999:999 ./local/pgdata
      - ./local/pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U My3xTr4S3cur3U53r -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - odoo:dev
    # image: odoo
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - CONFIG_FILE=/opt/odoo/local/odoo.conf
    volumes:
      - ./:/opt/odoo

# docker run -d --name db \
#     -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres \
#     -v $(pwd)/pgdata:/var/lib/postgresql/data \
#     postgres:15

# docker run --name odoo -p 8069:8069 --link db:db \
#     -v $(pwd)/odoo/modules:/usr/lib/python3/dist-packages/odoo/modules \
#     -t odoo